version: '3.1'

services:

  minio:
    image: minio/minio
    container_name: minio
    command: "server /data"
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: changeme
    volumes:
      - /mnt/data:/data
